[Wasabi-December]
type = s3
provider = Wasabi
access_key_id = FUK9EL8LR0T34XJJJ8NH
secret_access_key = bsy0t2L7LEBuriFkAptzZF127iWunrF8j3zED2qM
endpoint = s3.us-east-1.wasabisys.com
acl = public-read-write

[Wasabi-November]
type = s3
provider = Wasabi
access_key_id = 905ZSI8ER7DAL7HJSM9O
secret_access_key = LE5Bsm1KAcKHDwRyKI9kHzmSN7VYkeAX6mVau9Pt
endpoint = s3.us-central-1.wasabisys.com
acl = public-read-write

