[Wasabi-December]
type = s3
provider = Wasabi
access_key_id = REDACTED_ROTATE_ME
secret_access_key = REDACTED_ROTATE_ME
endpoint = s3.us-east-1.wasabisys.com
acl = public-read-write

[Wasabi-November]
type = s3
provider = Wasabi
access_key_id = REDACTED_ROTATE_ME
secret_access_key = REDACTED_ROTATE_ME
endpoint = s3.us-central-1.wasabisys.com
acl = public-read-write

