# F-OFF Mode to give the democratic choice of doing what the F I want.

# Define variable inside the file to be safe
$mainMod = SUPER

# Enter "Move Mode"
bind = $mainMod, M, submap, move_mode

submap = move_mode

# Use 'bindm' for dragging/resizing
# We add the 'e' flag to ensure it's handled as an active event
bindm = , mouse:272, movewindow
bindm = , mouse:273, resizewindow

# IMPORTANT: Catch-all to get the hell out
bind = , escape, submap, reset
bind = $mainMod, M, submap, reset

submap = reset
